[manager]
show_hidden = true
ratio = [ 1, 3, 4 ]
linemode = "size"

[opener]
edit = [
	{ run = 'notepad++ %*', desc = "Notepad++", for = "windows" },
	{ run = 'notepad %*', desc = "Notepad", for = "windows" },
    { run = 'nvim %*', block = true, desc = "nvim", for = "windows" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
	{ run = 'open -a TextEdit "$@"', desc = "TextEdit", for = "macos" },
	{ run = 'nano "$@"', desc = "nano",  block = true, for = "unix" },
	{ run = 'nvim "$@"', desc = "nvim",  block = true, for = "unix" },
]
extract = [
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
] 
