$apps = @(
  "Mozilla.Firefox",
  "Google.Chrome",
  "VideoLAN.VLC",
  "Microsoft.PowerToys",
  "Microsoft.VisualStudioCode",
  "7zip.7zip",
  "Git.Git",
  "Notepad++.Notepad++",
  'Neovim.Neovim',
  'AutoHotkey.AutoHotkey',
  'RustDesk.RustDesk',
  'AntibodySoftware.WizTree',
  'SoftDeluxe.FreeDownloadManager',
  'TheDocumentFoundation.LibreOffice',
  'wez.wezterm',
  'PuTTY.PuTTY',
  'SoftMaker.FreeOffice',
  'Mobatek.MobaXterm',
  'Microsoft.PowerShell',
  'Bruno.Bruno',
  'DBeaver.DBeaver.Community',
  'JesseDuffield.lazygit',
  'Postman.Postman',
  'Atlassian.Sourcetree',
  'Zoom.Zoom',
  'ajeetdsouza.zoxide',
  'junegunn.fzf',
  'sharkdp.bat',
  'sharkdp.fd',
  'sxyazi.yazi',
  'twpayne.chezmoi',
  'LocalSend.LocalSend',
  'twpayne.chezmoi',
  'ZedIndustries.Zed',
  'VSCodium.VSCodium',
  'MartiCliment.UniGetUI',
  'Microsoft.Teams',
  'Microsoft.WindowsTerminal'
  
)

$apps | ForEach-Object { winget install --id $_ --exact --accept-source-agreements --accept-package-agreements }
