[manager]
show_hidden = true
ratio = [ 1, 3, 4 ]
linemode = "size"

[opener]
edit = [
	{ run = 'notepad++ %*', desc = "Notepad++", for = "windows" },
	{ run = 'notepad %*', desc = "Notepad", for = "windows" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
	{ run = 'open -a TextEdit "$@"', desc = "TextEdit", for = "macos" },
	{ run = 'nano "$@"', desc = "nano",  block = true, for = "unix" },
	{ run = 'nvim "$@"', desc = "nvim",  block = true, for = "unix" },
]